# Gateway Configuration:
server:
  port: ${SERVER_PORT}

# Gateway Routes:
spring:
  cloud:
    gateway:
      routes:
        - id: Ejemplo_Borrar
          uri: http://localhost:4000
          predicates:
            - Path=/hola/**
          filters:
            - AuthFilter
        - id: LoginRegister
          uri: https://twitsnap-auth-api.onrender.com
          predicates:
            - Path=/v1/auth/**
