# Gateway Configuration:
server:
  port: ${SERVER_PORT}

# Gateway Routes:
spring:
  cloud:
    gateway:
      routes:
        - id: Auth-[auth,logIn,register,password]
          uri: ${AUTH_MS_URI}
          predicates:
            - Path=/v1/auth/**
            
        - id: Users-[Interests]
          uri: ${USERS_MS_URI}
          predicates: 
            - Path=/api/v1/interests/

        - id: Users-[users]
          uri: ${USERS_MS_URI}
          predicates: 
            - Path=/api/v1/users/**
          filters:
            - AuthFilter

        - id: Users-[Register]
          uri: ${USERS_MS_URI}
          predicates:
            - Path=/api/v1/register/**

        - id: Twits
          uri: ${TWIT_MS_URI}
          predicates:
            - Path=/v1/twit/**
          filters:
            - AuthFilter
            
        - id: Chat-[API Websocket]
          uri: ${CHAT_MS_WS_URI}
          predicates:
            - Path=/api/v1/chats/websocket
          filters:
            - AuthFilter
            
        - id: Chat-[API Rest]
          uri: ${CHAT_MS_URI}
          predicates:
            - Path=/api/v1/chats/**
          filters:
            - AuthFilter
