# Gateway Configuration:
server:
  port: ${SERVER_PORT}

# Logger Configuration:
logging:
  file:
    name: ${LOG_PATH}
  level:
    org.springframework.cloud.gateway: ${LOG_LEVEL}

# Gateway Routes:
spring:
  cloud:
    gateway:
      routes:
        - id: my_route
          uri: http://localhost:8080
          predicates:
            - Path=/my_route/**