# Gateway Configuration:
server:
  port: ${SERVER_PORT}

# Gateway Routes:
spring:
  cloud:
    gateway:
      routes:
        - id: Auth-[auth,logIn,register]
          uri: https://twitsnap-auth-api.onrender.com
          predicates:
            - Path=/v1/auth/**
        - id: Users-[users]
          uri: https://twitsnap-user-api-af1u.onrender.com
          predicates: 
            - Path=/api/v1/users/**
          filters:
            - AuthFilter
        - id: Users-[Register]
          uri: https://twitsnap-user-api-af1u.onrender.com
          predicates:
            - Path=/api/v1/register/**


