scrape_configs:
  - job_name: 'Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:8081']
        labels:
          application: 'My Spring Boot Application'

remote_write:
  - url: "https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push"
    basic_auth:
      username: "1942844"
      password: ${GRAFANA_KEY}
