global:
  scrape_interval: 60s
remote_write:
  - url: https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push
    basic_auth:
      username: 1942844
      password: ${GRAFANA_KEY}
scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["localhost:9090"]
